### ISSUE TITLE
Add style hash to Element prototype

### ISSUE THREAD

**Issue by taras** [krisselden/simple-dom#10]
I'm using `simple-dom` with a library that sets styles onto elements by setting attributes on style hash. It blows up when style hash is not available. It seems reasonable for the library to expect the style hash to exist. I can add the style hash in my code but it seems like it should be included on the prototype. 

Would you accept a PR that adds style hash to Element prototype?

**Comment by krisselden** [comment]
@taras you can import Element and add it to the prototype, in order to add style.  The style property is not just simply a hash, it is a CSSStyleDeclaration and further complicates the data structure.  Maybe if we add support to do bindings within css that are safe, like adding CSSBars to HTMLBars I'd consider it.
